"""Pydantic schemas for Agent Reasoning, Trajectories, Events, and Solver API."""

from typing import Any, Literal

from pydantic import BaseModel, Field

AgentEventType = Literal[
    "agent.started",
    "agent.thinking",
    "agent.planning",
    "agent.tool.started",
    "agent.tool.completed",
    "agent.file.changed",
    "agent.test.started",
    "agent.test.completed",
    "agent.approval_required",
    "agent.completed",
    "agent.error",
]


class FileChange(BaseModel):
    """File change item tracking modified, added, or deleted files."""

    file_path: str = Field(..., description="Relative file path modified in workspace")
    change_type: Literal["added", "modified", "deleted"] = Field(
        ..., description="Type of change"
    )
    content_snippet: str | None = Field(default=None, description="Snippet or diff preview")


class TestResultData(BaseModel):
    """Test execution result summary."""

    total_tests: int = Field(default=0, description="Total tests executed")
    passed: int = Field(default=0, description="Passed test count")
    failed: int = Field(default=0, description="Failed test count")
    output: str = Field(..., description="Pytest standard output text")


class AgentEvent(BaseModel):
    """Real-time event payload for SSE streaming."""

    event_id: str = Field(..., description="Unique event identifier")
    task_id: str = Field(..., description="Task or session identifier")
    event_type: AgentEventType = Field(..., description="Typed event name")
    timestamp: str = Field(..., description="ISO 8601 event timestamp")
    data: dict[str, Any] = Field(default_factory=dict, description="Payload data")


class AgentPlanStep(BaseModel):
    """Individual thought and action step in the agent reasoning trajectory."""

    step_number: int = Field(..., ge=1, description="Sequential step index")
    thought: str = Field(..., description="Agent reasoning thought process")
    tool_name: str | None = Field(default=None, description="Target tool invoked in this step")
    tool_params: dict[str, Any] | None = Field(
        default=None, description="Parameters passed to tool"
    )
    status: Literal["pending", "executing", "completed", "failed"] = Field(
        default="pending", description="Step execution status"
    )
    observation: str | None = Field(
        default=None, description="Result or output observed from tool execution"
    )


class AgentPlan(BaseModel):
    """High-level plan generated by cognitive engine."""

    goal: str = Field(..., description="Original user goal string")
    steps: list[AgentPlanStep] = Field(default_factory=list, description="Planned step sequence")
    status: Literal["in_progress", "completed", "failed"] = Field(
        default="in_progress", description="Overall plan status"
    )


class ReasoningRequest(BaseModel):
    """Payload model for requesting autonomous goal resolution."""

    goal: str = Field(..., min_length=3, description="High-level engineering task or request")
    context: str | None = Field(
        default=None, description="Optional extra background context or instructions"
    )
    max_iterations: int = Field(
        default=5, ge=1, le=10, description="Maximum ReAct reasoning iterations"
    )
    provider: Literal["mock", "gemini", "openai"] | None = Field(
        default=None, description="Override LLM provider"
    )
    model: str | None = Field(default=None, description="Override model identifier")


class ReasoningResponse(BaseModel):
    """Output model containing trajectory and final answer."""

    goal: str = Field(..., description="Target goal solved")
    final_answer: str = Field(..., description="Synthesized final resolution or summary")
    trajectory: list[AgentPlanStep] = Field(
        ..., description="Complete step-by-step reasoning trajectory"
    )
    total_iterations: int = Field(..., ge=1, description="Total iterations executed")
    execution_time_ms: float = Field(..., description="Execution duration in milliseconds")
    timestamp: str = Field(..., description="ISO 8601 server completion timestamp")
